{% set name = "isce3" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/isce-framework/isce3/archive/v{{ version }}.tar.gz
  sha256: 54da2b3d1f95aaed461b70c3f5fcb6e909e3d23bc19b2bdc7d3646f10b73d675
  patches:
    # Fix pytest PYTHONPATH
    - fix-destdir.patch

build:
  number: 0
  skip: true  # [win or py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - cython
    - eigen
    - fftw
    - gdal
    - gmock
    - gtest
    - numpy
    - pybind11
    - python
    - pyre

    # Needed for ctests in build.sh
    - h5py
    - pytest
    - ruamel.yaml
    - shapely
    - yamale
  run:
    - fftw
    - gdal
    - h5py
    - hdf5
    - libgdal
    - llvm-openmp  # [osx]
    - {{ pin_compatible('numpy') }}
    - _openmp_mutex  # [not osx]
    - pyre
    - python
    - ruamel.yaml
    - shapely
    - yamale

test:
  imports:
    - isce3
    - nisar
    - pybind_isce3
    - pybind_nisar

about:
  home: https://github.com/isce-framework/isce3
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: The InSAR Scientific Computing Environment, version 3

  description: |
    The InSAR Scientific Computing Environment (ISCE) is an open source library
    for processing spaceborne and airborne Interferometric Synthetic Aperture
    Radar (InSAR) data.
    This project is a successor to the ISCE2 framework. It is a ground-up
    redesign focusing on improved modularity, documentation, and test-driven
    development.

  doc_url: https://isce-framework.github.io/isce3
  dev_url: https://github.com/isce-framework/isce3

extra:
  recipe-maintainers:
    - rtburns-jpl
