{% set name = "isce3" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/isce-framework/isce3/archive/v{{ version }}.tar.gz
  sha256: d371f57198303d54c1c9c0b95663998ab09527b0b126cee2db3afb8b1317fe2b

build:
  number: 0
  skip: true  # [win or py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - eigen
    - fftw
    - gdal
    - gmock
    - gtest
    - numpy
    - pybind11
    - python
    - pyre

    # Needed for ctests in build.sh
    - h5py
    - pytest
    - ruamel.yaml
    - scipy
    - shapely
    - yamale
  run:
    - fftw
    - gdal
    - h5py
    - hdf5
    - libgdal
    - llvm-openmp  # [osx]
    - {{ pin_compatible('numpy') }}
    - _openmp_mutex  # [not osx]
    - pyre
    - python
    - ruamel.yaml
    - scipy
    - shapely
    - yamale

test:
  requires:
    - cmake
  commands:
    - ctest --output-on-failure -E '(workflows.stage_dem|pybind.focus.presum)'
  imports:
    - isce3
    - pybind_isce3

about:
  home: https://github.com/isce-framework/isce3
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: The InSAR Scientific Computing Environment, version 3

  description: |
    The InSAR Scientific Computing Environment (ISCE) is an open source library
    for processing spaceborne and airborne Interferometric Synthetic Aperture
    Radar (InSAR) data.
    This project is a successor to the ISCE2 framework. It is a ground-up
    redesign focusing on improved modularity, documentation, and test-driven
    development.

  doc_url: https://isce-framework.github.io/isce3
  dev_url: https://github.com/isce-framework/isce3

extra:
  recipe-maintainers:
    - rtburns-jpl
